FROM registry.access.redhat.com/ubi8/openjdk-21:1.20

ENV LANGUAGE='en_US:en'

USER root

# Installiere Maven
RUN microdnf install maven

# Setze Arbeitsverzeichnis
WORKDIR /app

# Kopiere das Projekt
COPY --chown=185:185 . .

# Exponiere den Port
EXPOSE 8080
EXPOSE 5005

# Setze Umgebungsvariablen
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV MAVEN_OPTS="-Xmx1g"

USER 185

# Starte Quarkus im Dev-Modus
CMD ["./mvnw", "quarkus:dev", "-Dquarkus.http.host=0.0.0.0"] 