@startuml cura
title cura

entity "Person" as person {
    +PersonId : int PRIMARY KEY
    --
    firstName : varchar(100)
    lastName : varchar(100)
    phoneNumber : varchar(15)
    addressId : int
}

entity "Patient" as patient {
    +PatientId : int PRIMARY KEY
    --
    personId : int
}

entity "ContactPerson" as contactPerson {
    +ContactPersonId : int PRIMARY KEY
    --
    personId : int
}

entity "CaresFor" as caresFor {
    patientId : int
    contactPersonId : int
    contactTypeId : int
    PRIMARY KEY (patientId, contactPersonId)
}

entity "Address" as address {
    +AddressId : int PRIMARY KEY
    --
    country : varchar(100)
    state : varchar(100)
    city : varchar(100)
    street : varchar(100)
    houseNumber : int
    stair : int
    floor : int
    doorNumber : int
    addressExtra : varchar(100)
}

entity "Medicament" as medicament {
    +MedicamentId : int PRIMARY KEY
    --
    medicamentName : varchar(100)
    description : varchar(100)
}

entity "MedicationPlan" as medicationPlan {
    +MedicationPlanId : int PRIMARY KEY
    --
    patientId : int
    startDate : date -- (optional)
    endDate : date -- (optional)
}

entity "MedicationPlan_Medicament" as medPlanMedicament {
    +MedicationPlanId : int
    +MedicamentId : int
    --
    timeSlot : enum -- (08:00, 12:00, 16:00, 20:00)
    dayOfWeek : enum -- (Monday, Tuesday,...)
    amountOfMedicament : int
    PRIMARY KEY (MedicationPlanId, MedicamentId, timeSlot, dayOfWeek)
}

entity "PillBoxOpening" as medicationLog {
    +LogId : int PRIMARY KEY
    --
    medicationPlanId : int
    timestamp : timestamp -- Timestamp of the actual intake
    drawerId : int -- Reference to the drawer or tag
}

caresFor }|--|| contactPerson
caresFor }|--|| patient

contactPerson ||--|| person
patient ||--|| person

medicationPlan }|--|| patient
medicationPlan ||--o{ medPlanMedicament
medicament ||--o{ medPlanMedicament

person ||--|| address
@enduml
