@startuml leo


cloud "Home Network" {
  node "ESP32" {
    component "Medication Box Detection" as MedicationBox
  }

  node "Raspberry Pi" {
    database "Database" as DB {
      frame "Medication Data" as MedicationData
      frame "User Profiles" as UserProfiles
      frame "Medical Status" as MedicalStatus
    }
    component "Home Assistant" as HomeAssistant
    component "MQTT Broker" as MQTTBroker
  }
  component "Mobile Phone" as MobilePhone1
}

cloud "External Network" {
  component "Mobile Phone" as MobilePhone2
}

MedicationBox --> MQTTBroker : pill box event
MQTTBroker <--> HomeAssistant : Receives pill status
HomeAssistant <--> DB
HomeAssistant --> MobilePhone1 : Sends notification if late
HomeAssistant --> MobilePhone2 : Sends notification if late

@enduml
