@startuml cura
title cura

entity "Person" as person {
    +PersonId : int PRIMARY KEY
    --
    firstName : varchar(100)
    lastName : varchar(100)
    phoneNumber : varchar(15)
    addressId : int
}

entity "Patient" as patient {
    +PatientId : int PRIMARY KEY
    --
    personId : int
}

entity "ContactPerson" as contactPerson{
    +ContactPersonId : int PRIMARY KEY
    --
    personId : int
}

entity "CaresFor" as caresFor{
    patientId : int
    contactPersonId : int
    contactTypeId : int
}

entity "ContactType" as contactType{
    +ContactTypeId : int PRIMARY KEY
    --
    description : varchar(200)
}

entity "Address" as location{
    +AddressId : int PRIMARY KEY
    --
    country : varchar(100)
    state : varchar(100)
    city : varchar(100)
    street : varchar(100)
    houseNumber : int
    stair : int
    floor : int
    doorNumber : int
    addressExtra : varchar(100)
}

entity "Medicament" as medicament{
    +MedicamentId : int PRIMARY KEY
    --
    medicamentName : varchar(100)
    description : varchar(100)
}

entity "Medication" as plan{
    +medicamentPlanId : int
    --
    medicamentId : int
    patientId : int
    MedicationTime : timestamp
    timeSlot : VARCHAR2(5) (08:00, 12:00, 16:00, 20:00)
    dayOfWeek : NUMBER(1) (1:Monday, 2:Tuesday, ..)
    amountOfMedicament : int
    startDate : (optional)
    endDate : (optional)
}

caresFor }|--|| contactPerson
caresFor }|--|| patient
contactPerson ||--|| person
patient ||--|| person
plan ||--|| patient
medicament }|--|{ plan
person ||--|| location
contactType }|--|{ caresFor

@enduml
