= Besprechungsprotokoll 12.02.2025
Elias Mahr

.Teilnehmer
|===
|Anwesend 
|M. Palitsch-Infanger
|T. Stuetz
|L. Mistelberger
|T. Schmalzer
|E. Mahr
|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Klasse

|Datum
|Mi. 26.02.2025
|Dauer
|50 min
|===



== Besprochene Themen

* Project Tablettenschachtel


== Vereinbarungen und Entscheidungen

.Was wurde vereinbart?
[%autowidth]
|===
|wer |macht was 

| Project Tem
a| 
Die Tablettenschachtel soll an fix gelegten Zeiten checken ob die Medikamente genommen wurden wenn nicht werden folgenden Signale ausgelöst: 

* Visuelle Hinweise mit: 
** Display auf der Schachtel
** Meldung am Fernseher
* Auditiv:
** ein Lautsprecher der einfache Töne von sich gibt z.B. Pipipip

Als erweiterung kommt später noch eine Website die vom Esp32 selbst gehostet wird die die folgenden funktionen enthält:

* änderung des Zeitpunks der Medikamenten Einnahme
* Abschnit zur verwaltung der Notfallkontakte in dem mann Nummern hinzu und weg geben kann. Die bei nicht einnahme über Whatsapp kontaktiert werden. Optional kann noch entschieden werden ob die Kontakte auch bei Einnahme des Medikaments kontaktiert werden wollen.

|===
